title: "R Foundations for Live Scientists workshop" 
baseurl: /workshop-r

# where things are
layouts_dir: ./workshop-common/layouts
includes_dir: ./workshop-common/includes
sass:
  sass_dir: ./workshop-common/sass

plugins:
  - jemoji

defaults:
  - values:
      logosnav: true

menu:
  - title: Overview
    url:
  - title: Schedule
    url: schedule
  - title: Pre-course material
    url: precourse
  - title: Travel info
    url: travel
  - title: Labs
    submenus:
      - title: Lab 1
        url: labs/lab1
      - title: Lab 2
        url: labs/lab2